### ISSUE TITLE
PPSSPP compatability

### ISSUE THREAD

**Issue by jmoseman01** [bearzly/XInputEmu#1]
I'm trying to do socket programming against ppsspp with this and it doesn't seem to work.  I don't see the dll listed, but it does use XInput, can you help me?

**Comment by bearzly** [comment]
Hey, acknowledged. I haven't look at this code in a while but I'd be happy to try to get it working on PPSSPP when I have some time.

**Comment by jmoseman01** [comment]
Heck yes!

**Comment by bearzly** [comment]
Just a question though - PPSSPP is open source and provides its own input abstraction layer. Are you sure whatever you're trying to do wouldn't be easier to write as an input module directly in PPSSPP?

**Comment by jmoseman01** [comment]
Nice find!  I'll see if I can build a socket receiver on top of that.

**Comment by jmoseman01** [comment]
I was viewing the source code and it looks like they're just loading the xinput.dll file.
```c++
s_pXInputDLL = LoadLibrary( L"XInput1_4.dll" );  // 1.4 Ships with Windows 8.
	if (!s_pXInputDLL) {
		version = (1 << 16) | 3;
		s_pXInputDLL = LoadLibrary( L"XInput1_3.dll" );  // 1.3 Ships with Vista and Win7, can be installed as a restributable component.
		if (!s_pXInputDLL) {
			version = (1 << 16) | 0;
			s_pXInputDLL = LoadLibrary( L"XInput9_1_0.dll" );  // 1.0 ships with any Windows since WinXP
		}
	}
```

**Comment by jmoseman01** [comment]
Do you think we can use your hook and just load it agains XInput1_4.dll?

**Comment by jmoseman01** [comment]
Does this still hold true - "I believe you need a real XInput device plugged in (i.e. Xbox 360 controller), but that could be worked around"

**Comment by jmoseman01** [comment]
I was able to hard code XInput1_4.dll instead of what you had and get a socket connection, but I think it didn't work due to the fact that you need an xbox controller plugged in.  Is this a good assumption?

**Comment by jmoseman01** [comment]
I got ViGEm to work!

https://github.com/ViGEm
